// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ITableCellCss {
  'TableCell': string;
  'TableCell--head': string;
  'TableCell--head__sorting': string;
}

export const locals: ITableCellCss;
