// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ITextInputCss {
  'TextInput': string;
  'TextInput__input': string;
  'TextInput--small': string;
  'TextInput--medium': string;
  'TextInput--large': string;
  'TextInput--full': string;
  'TextInput--disabled': string;
  'TextInput--negative': string;
  'TextInput__copy-button': string;
}

export const locals: ITextInputCss;
