// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ITextLinkCss {
  'TextLink': string;
  'TextLink--primary': string;
  'TextLink--positive': string;
  'TextLink--negative': string;
  'TextLink--secondary': string;
  'TextLink--muted': string;
  'TextLink--disabled': string;
  'TextLink__icon': string;
  'TextLink__icon-wrapper': string;
}

export const locals: ITextLinkCss;
