// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ICopyButtonCss {
  'CopyButton': string;
  'CopyButton__button': string;
  'CopyButton__text': string;
  'CopyButton__TabFocusTrap': string;
}

export const locals: ICopyButtonCss;
