// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IA11yCss {
  'focus-outline--default': string;
  'focus-border--default': string;
}

export const locals: IA11yCss;
