// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ISelectFieldCss {
  'SelectField': string;
  'SelectField__label-wrapper': string;
  'SelectField__label-link': string;
  'SelectField__validation-message': string;
  'SelectField__help-text': string;
}

export const locals: ISelectFieldCss;
