// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ISkeletonContainerCss {
  'SkeletonContainer': string;
}

export const locals: ISkeletonContainerCss;
