const path = require('path');
const fs = require('fs');

let template = `/**
 * This file is autogenerated by a build script, don't change it manually.
 */

export type {
  GeneratedIconProps as IconProps,
  IconComponent,
  IconSize,
  IconVariant,
} from '@contentful/f36-icon';\n`;

(function () {
  fs.readdir(path.join('.', 'src'), (error, allFiles) => {
    if (error) {
      console.log('error reading icons:');
      console.log(error);
    }

    const icons = allFiles
      .filter((file) => file.endsWith('.tsx'))
      .map((file) => file.replace('.tsx', ''));

    for (const icon of icons) {
      template =
        template + `export { ${icon} as ${icon}Icon } from './${icon}';\n`;
    }

    fs.writeFile(
      path.join('.', 'src/index.ts'),
      template,
      {
        encoding: 'utf-8',
      },
      (error) => {
        if (error) {
          console.log('error writing icons index file:');
          console.log(error);
        }
      },
    );
  });
})();
