// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ITooltipCss {
  'Tooltip__target-wrapper': string;
  'Tooltip': string;
  'Tooltip--hidden': string;
  'Tooltip--place-bottom': string;
  'Tooltip--place-top': string;
  'Tooltip--place-left': string;
  'Tooltip--place-right': string;
}

export const locals: ITooltipCss;
