packages:
  - 'packages/*'
  - 'packages/components/*'

linkWorkspacePackages: true
autoInstallPeers: false
minimumReleaseAge: 21600
ignoreScripts: true

overrides:
  '@emotion/eslint-plugin>eslint': '>=9.0.0'
  'react-day-picker>react': '>=19.1.0'
