// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface INoteCss {
  'Note': string;
  'Note--primary': string;
  'Note--negative': string;
  'Note--positive': string;
  'Note--warning': string;
  'Note__title': string;
  'Note__icon': string;
}

export const locals: INoteCss;
