// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ITextareaCss {
  'Textarea': string;
  'Textarea__textarea': string;
  'Textarea--small': string;
  'Textarea--medium': string;
  'Textarea--large': string;
  'Textarea--full': string;
  'Textarea--disabled': string;
  'Textarea--negative': string;
}

export const locals: ITextareaCss;
