// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ITypographyCss {
  'Typography': string;
}

export const locals: ITypographyCss;
