// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IEditorToolbarButtonCss {
  'EditorToolbarButton': string;
  'EditorToolbarButton--is-active': string;
}

export const locals: IEditorToolbarButtonCss;
