// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ICommandPanelCss {
  'CommandPanel': string;
  'CommandPanel__item': string;
  'CommandPanel__divider': string;
  'CommandPanel__item--is-selected': string;
}

export const locals: ICommandPanelCss;
