// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IModalControlsCss {
  'ModalControls': string;
}

export const locals: IModalControlsCss;
