export { DisplayText } from './DisplayText/DisplayText';
export type { DisplayTextProps } from './DisplayText/DisplayText';
export { Heading } from './Heading/Heading';
export type { HeadingProps } from './Heading/Heading';
export { Paragraph } from './Paragraph/Paragraph';
export type { ParagraphProps } from './Paragraph/Paragraph';
export { SectionHeading } from './SectionHeading/SectionHeading';
export type { SectionHeadingProps } from './SectionHeading/SectionHeading';
export { Subheading } from './Subheading/Subheading';
export type { SubheadingProps } from './Subheading/Subheading';
export { Typography } from './Typography/Typography';
export type { TypographyProps } from './Typography/Typography';
