// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ISubheadingCss {
  'Subheading': string;
}

export const locals: ISubheadingCss;
