import type { EntityStatus } from '@contentful/f36-components';

export type LongContentRow = {
  id: string;
  name: string;
  status: EntityStatus;
  contentType: string;
  updatedBy: string;
  updated: string;
  locale: string;
  space: string;
  environment: string;
  tags: string;
};

const statuses: EntityStatus[] = [
  'published',
  'changed',
  'draft',
  'archived',
  'deleted',
];
const contentTypes = [
  'Blog post',
  'Landing page',
  'Product',
  'Author',
  'Category',
  'FAQ',
  'Press release',
  'Case study',
  'Testimonial',
  'Event',
];
const authors = [
  'Ayman Mahmoud',
  'Jane Roe',
  'John Doe',
  'Alice Kim',
  'Bob Müller',
  'Carlos Rivera',
  'Diana Chen',
  'Erik Larsson',
  'Fatima Al-Hassan',
  'Grace Okafor',
];
const locales = ['en-US', 'de-DE', 'fr-FR', 'es-ES', 'pt-BR'];
const spaces = ['Marketing', 'E-Commerce', 'Documentation', 'Blog', 'Support'];
const environments = ['master', 'staging', 'development'];
const tagSets = [
  'featured, trending',
  'evergreen',
  'seasonal, campaign',
  'internal',
  'partner',
  '',
  'seo-optimized',
  'draft, review',
  'localization-ready',
  'archived-2024',
];
const timeAgo = [
  'Just now',
  '5 minutes ago',
  '2 hours ago',
  'Yesterday',
  '3 days ago',
  'Last week',
  '2 weeks ago',
  '1 month ago',
  '6 months ago',
  '11 months ago',
];
const names = [
  'How does writing influence your personal brand?',
  'How to optimize images in WordPress for faster loading (complete guide)',
  'Travelling as a way of self-discovery and progress',
  'Start a blog to reach your creative peak',
  'Why choose a theme that looks good with WooCommerce',
  'Top 10 productivity tools for remote teams in 2025',
  'The ultimate guide to headless CMS architecture',
  'Building accessible web applications from the ground up',
  'Content strategy for B2B SaaS companies',
  'How to reduce churn with better onboarding experiences',
  'A/B testing your landing pages: a practical guide',
  'SEO fundamentals every content team should know',
  'Designing for dark mode: tips and pitfalls',
  'Microservices vs monoliths: which is right for you?',
  'Introduction to GraphQL for frontend developers',
  'Scaling content operations across multiple markets',
  'The role of structured content in omnichannel delivery',
  'Managing multilingual content with a headless CMS',
  'How to audit your content for accessibility issues',
  'Performance budgets: keeping your site fast',
  'Progressive enhancement in modern web development',
  'Why composable architecture is the future of digital',
  'Getting started with edge computing',
  'A deep dive into Core Web Vitals',
  'Building design systems that scale',
  'Integrating third-party APIs into your CMS workflow',
  'Content modeling best practices for large teams',
  'From monolith to composable: a migration story',
  'How to measure content ROI effectively',
  'The business case for accessibility',
  'React Server Components explained',
  'Next.js 15: what changed and what it means for you',
  'Astro vs Next.js: a fair comparison',
  'Turbopack first impressions',
  'Deploying to the edge with Cloudflare Workers',
  'Feature flags: from concept to production',
  'Continuous delivery for content teams',
  'How platform teams enable developer productivity',
  'Observability for frontend engineers',
  'Error budgets and SLOs in practice',
  'Building resilient systems with circuit breakers',
  'The anatomy of a great error message',
  'Writing documentation developers actually read',
  'Technical writing as a core engineering skill',
  'How to run effective architecture review boards',
  'Incident management playbooks for fast-moving teams',
  'Postmortems without blame: a practical guide',
  "On-call rotations that don't burn out your team",
  'The hidden costs of technical debt',
  'Refactoring legacy code safely with strangler fig',
  'How to prioritize a technical backlog',
  'Engineering metrics that actually matter',
  'Hiring senior engineers: what to look for',
  'Onboarding engineers in distributed teams',
  'Remote-first culture: lessons from two years in',
  'Async communication patterns for global teams',
  'How to give feedback that sticks',
  'Running better one-on-ones as an engineering manager',
  "OKRs for engineering teams: a skeptic's guide",
  'The art of the technical roadmap',
  'Product thinking for engineers',
  'Why platform engineering is having a moment',
  'Internal developer platforms: build vs buy',
  'Developer experience: the metrics that matter',
  'API versioning strategies compared',
  'Webhook security best practices',
  'OAuth 2.0 flows demystified',
  'Zero-trust networking for startups',
  'Supply chain security in the npm ecosystem',
  'Static analysis tools worth adding to your pipeline',
  'Code review culture: beyond nitpicks',
  'Pair programming in an async world',
  'Mob programming: when the whole team codes together',
  'Test-driven development in practice',
  'Property-based testing with fast-check',
  'Visual regression testing at scale',
  'End-to-end testing without the flakiness',
  'Component testing: the sweet spot',
  'Contract testing with Pact',
  'Chaos engineering for the cautious',
  'Load testing your APIs before launch',
  'Database migrations without downtime',
  'Postgres full-text search: a practical primer',
  'When to reach for Redis',
  'Event sourcing and CQRS: a gentle introduction',
  'Designing for eventual consistency',
  'The CAP theorem revisited',
  'Stream processing with Kafka in plain English',
  'Data pipelines for product analytics',
  'Building a metrics platform from scratch',
  'Structuring logs for observability',
  'Distributed tracing with OpenTelemetry',
  'Alerting that wakes the right person',
  'SRE principles applied to small teams',
  'FinOps: controlling cloud spend without slowing down',
  "Kubernetes for teams that don't have an SRE",
  'Terraform in practice: patterns and anti-patterns',
  'GitOps with ArgoCD: a walkthrough',
  'Multi-cloud strategies: pros, cons, and tradeoffs',
  'Green software engineering: reducing your carbon footprint',
  'AI-assisted coding: a year of daily use',
  'Prompt engineering for developers',
];

export const withLongContentTableData: LongContentRow[] = Array.from(
  { length: 15 },
  (_, i) => ({
    id: `entry-${i + 1}`,
    name: names[i % names.length],
    status: statuses[i % statuses.length],
    contentType: contentTypes[i % contentTypes.length],
    updatedBy: authors[i % authors.length],
    updated: timeAgo[i % timeAgo.length],
    locale: locales[i % locales.length],
    space: spaces[i % spaces.length],
    environment: environments[i % environments.length],
    tags: tagSets[i % tagSets.length],
  }),
);
