// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IDisplayTextCss {
  'DisplayText': string;
  'DisplayText--default': string;
  'DisplayText--large': string;
}

export const locals: IDisplayTextCss;
