// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IColorSwatchCss {
  'ColorSwatch': string;
  'ColorSwatch__swatch': string;
  'ColorSwatch__label': string;
  'ColorSwatch__name': string;
  'ColorSwatch__hex': string;
  'ColorSwatch__css-var': string;
}

export const locals: IColorSwatchCss;
