blank_issues_enabled: false
contact_links:
  - name: Contentful Community Slack
    url: https://www.contentful.com/slack/
    about: "Reach out to us on Contentful Community Slack for any questions, we're in the #forma36 channel"
