blank_issues_enabled: false
contact_links:
  - name: Contentful Community Discord
    url: https://www.contentful.com/discord/
    about: "Reach out to us on Contentful Community Discord for any questions"
