// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IListItemCss {
  'ListItem': string;
  'ListItem--nested-list': string;
}

export const locals: IListItemCss;
