export const navigationIconName = {
  Apis: 'Apis',
  Apps: 'Apps',
  Billing: 'Billing',
  ContentModel: 'ContentModel',
  Content: 'Content',
  Home: 'Home',
  Media: 'Media',
  Oauth: 'Oauth',
  OrgInfo: 'OrgInfo',
  Oraganizations: 'Oraganizations',
  Settings: 'Settings',
  Spaces: 'Spaces',
  Sso: 'Sso',
  Subscription: 'Subscription',
  Teams: 'Teams',
  Token: 'Token',
  Usage: 'Usage',
  Users: 'Users',
  UserProfile: 'UserProfile'
};
