// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ISectionHeadingCss {
  'SectionHeading': string;
}

export const locals: ISectionHeadingCss;
