// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ICardCss {
  'Card': string;
  'Card--padding-default': string;
  'Card--padding-large': string;
  'Card--padding-none': string;
  'Card--is-interactive': string;
  'Card--is-selected': string;
}

export const locals: ICardCss;
