// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IDropdownListCss {
  'DropdownList': string;
  'DropdownList--border-top': string;
  'DropdownList--border-bottom': string;
}

export const locals: IDropdownListCss;
