// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IControlledInputFieldCss {
  'ControlledInputField': string;
  'ControlledInputField--disabled': string;
  'ControlledInputField__input': string;
  'ControlledInputField__label': string;
  'ControlledInputField__label--light': string;
}

export const locals: IControlledInputFieldCss;
