// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ITagCss {
  'Tag': string;
  'Tag--primary': string;
  'Tag--positive': string;
  'Tag--negative': string;
  'Tag--warning': string;
  'Tag--secondary': string;
  'Tag--muted': string;
}

export const locals: ITagCss;
