// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IAssetCss {
  'Asset': string;
  'Asset__image-container': string;
  'Asset__image-container__image': string;
  'Asset__title-container': string;
  'Asset__title-container__title': string;
  'Asset__asset-container': string;
  'Asset__asset-container__title': string;
  'Asset__illustration-container': string;
}

export const locals: IAssetCss;
