// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IDropdownListItemCss {
  'DropdownListItem': string;
  'DropdownListItem__toggle-button': string;
  'DropdownListItem__submenu-toggle': string;
  'DropdownListItem__toggle-button__inner-wrapper': string;
  'DropdownListItem--disabled': string;
  'DropdownListItem--active': string;
  'DropdownListItem--title': string;
}

export const locals: IDropdownListItemCss;
