// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ISpinnerCss {
  'Spinner': string;
  'rotate-cw': string;
  'Spinner--default': string;
  'Spinner--small': string;
  'Spinner--large': string;
  'Spinner--white': string;
}

export const locals: ISpinnerCss;
