// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IPillCss {
  'Pill': string;
  'Pill__label': string;
  'Pill__close-button': string;
  'Pill__drag-icon': string;
  'Pill__icon': string;
}

export const locals: IPillCss;
