// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IToggleButtonCss {
  'Toggle': string;
  'Toggle--active': string;
  'Toggle--disabled': string;
  'Toggle__button': string;
  'Toggle__button__icon': string;
  'Toggle__content-wrapper': string;
  'Toggle__button__inner-wrapper': string;
  'Toggle--square': string;
}

export const locals: IToggleButtonCss;
