// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IEditorToolbarDividerCss {
  'EditorToolbarDivider': string;
}

export const locals: IEditorToolbarDividerCss;
