// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IModalContentCss {
  'ModalContent': string;
}

export const locals: IModalContentCss;
