// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ITableHeadCss {
  'TableHead--sticky': string;
}

export const locals: ITableHeadCss;
