// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IFormLabelCss {
  'FormLabel': string;
  'FormLabel__required-text': string;
}

export const locals: IFormLabelCss;
