// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IControlledInputCss {
  'ControlledInput': string;
  'ControlledInput--disabled': string;
}

export const locals: IControlledInputCss;
