import type { NextPage } from 'next';

const NotAutoGenerated: NextPage = () => {
  return (
    <div>
      <h1>NotAutoGenerated</h1>

      <p>
        This is a TSX page, it was not generated from MDX files in components
        package
      </p>
    </div>
  );
};

export default NotAutoGenerated;
