// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IButtonCss {
  'Button': string;
  'Button--disabled': string;
  'Button__icon': string;
  'Button--full-width': string;
  'Button--muted': string;
  'Button--naked': string;
  'Button--primary': string;
  'Button__label': string;
  'Button--positive': string;
  'Button--negative': string;
  'Button__inner-wrapper': string;
  'Button--small': string;
  'Button--large': string;
  'Button__spinner': string;
  'Button--spinner--enter': string;
  'Button--spinner-active': string;
  'Button--spinner--exit': string;
  'Button--spinner-exit-active': string;
}

export const locals: IButtonCss;
