// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IDropdownContainerCss {
  'DropdownContainer': string;
  'DropdownContainer__submenu': string;
  'DropdownContainer__container-position--right': string;
  'DropdownContainer__container-position--left': string;
}

export const locals: IDropdownContainerCss;
