// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ITextFieldCss {
  'TextField': string;
  'TextField__label-wrapper': string;
  'TextField__label-link': string;
  'TextField__validation-message': string;
  'TextField__help-text': string;
  'TextField__hints': string;
  'TextField__count': string;
}

export const locals: ITextFieldCss;
