// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface INotificationItemCss {
  'NotificationItem': string;
  'NotificationItem--success': string;
  'NotificationItem--error': string;
  'NotificationItem--warning': string;
  'NotificationItem__intent': string;
  'NotificationItem__icon': string;
  'NotificationItem__text': string;
  'NotificationItem__dismiss': string;
}

export const locals: INotificationItemCss;
