// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface INotificationsManagerCss {
  'NotificationsManager': string;
  'NotificationsManager__container': string;
  'NotificationsManager--top': string;
}

export const locals: INotificationsManagerCss;
