// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IFieldGroupCss {
  'FieldGroup': string;
  'FieldGroup__item': string;
  'FieldGroup--row': string;
}

export const locals: IFieldGroupCss;
