// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IIconCss {
  'Icon': string;
  'Icon--tiny': string;
  'Icon--small': string;
  'Icon--large': string;
  'Icon--trimmed': string;
  'Icon--positive': string;
  'Icon--negative': string;
  'Icon--warning': string;
  'Icon--secondary': string;
  'Icon--muted': string;
  'Icon--white': string;
}

export const locals: IIconCss;
