// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ITabsCss {
  'Tabs': string;
  'Tab': string;
  'Tab__selected': string;
}

export const locals: ITabsCss;
