// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IModalHeaderCss {
  'ModalHeader': string;
  'ModalHeader__title': string;
  'ModalHeader__title--is-not-wrapped': string;
}

export const locals: IModalHeaderCss;
