// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ITransitionsCss {
  'slider': string;
  'slider__knob': string;
  'rotate-cw': string;
}

export const locals: ITransitionsCss;
