// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IFormCss {
  'Form': string;
  'Form__item': string;
  'Form__item--default': string;
  'Form__item--condensed': string;
}

export const locals: IFormCss;
