import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { geltAllMDX } from '../utils/content';

const Home: NextPage<{ components: { slug: string }[] }> = (props) => {
  console.log(props.components);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Forma 36 in Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.links}>
          <Link href="/getting-started">
            <a>Getting Started (the MDX file in /pages)</a>
          </Link>

          <Link href="/components/not-autogenerated">
            <a>Not auto generated page (the TSX in /pages)</a>
          </Link>
        </div>

        <h2>Pages generated from MDX files in /packages/components</h2>
        <ul>
          {props.components.map((component, idx) => {
            return (
              <li key={idx}>
                <Link href={`/components/${component.slug}`}>
                  <a>{component.slug}</a>
                </Link>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export async function getStaticProps() {
  const mdxData = await geltAllMDX();
  const sortedComponentsList = mdxData.sort((a, b) => {
    if (a.slug < b.slug) {
      return -1;
    }
    if (a.slug > b.slug) {
      return 1;
    }
    return 0;
  });

  return {
    props: {
      components: sortedComponentsList,
    },
  };
}

export default Home;
