// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IModalCss {
  'Modal__portal': string;
  'Modal__overlay': string;
  'Modal__overlay--after-open': string;
  'Modal__overlay--before-close': string;
  'Modal__overlay--centered': string;
  'Modal__wrap': string;
  'Modal__wrap--after-open': string;
  'Modal': string;
  'Modal__wrap--before-close': string;
  'Modal--overflow': string;
}

export const locals: IModalCss;
