// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IIconButtonCss {
  'IconButton': string;
  'IconButton__inner': string;
  'IconButton--disabled': string;
  'IconButton--primary': string;
  'IconButton__icon': string;
  'IconButton--positive': string;
  'IconButton--negative': string;
  'IconButton--secondary': string;
  'IconButton--muted': string;
  'IconButton--white': string;
  'IconButton__label': string;
  'IconButton__dropdown': string;
}

export const locals: IIconButtonCss;
