// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface ITableSortingLabelCss {
  'TableCell': string;
  'TableCell--head': string;
  'TableCell--head__sorting': string;
  'TableSortingLabel__button': string;
  'TableSortingLabel__button__text': string;
  'TableSortingLabel__icon': string;
  'TableSortingLabel__icon--asc': string;
  'TableSortingLabel__icon--desc': string;
}

export const locals: ITableSortingLabelCss;
