// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IInViewportCss {
  'InViewport': string;
}

export const locals: IInViewportCss;
