// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IValidationMessageCss {
  'ValidationMessage': string;
  'ValidationMessage__icon': string;
  'ValidationMessage__text': string;
}

export const locals: IValidationMessageCss;
