// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IInlineReferenceCardCss {
  'InlineReferenceCard': string;
  'InlineReferenceCard__skeleton-wrapper': string;
  'InlineReferenceCard__text-wrapper': string;
  'InlineReferenceCard__status-indicator': string;
  'InlineReferenceCard__status-indicator--published': string;
  'InlineReferenceCard__status-indicator--draft': string;
  'InlineReferenceCard__status-indicator--archived': string;
  'InlineReferenceCard__status-indicator--changed': string;
  'InlineReferenceCard__dropdown': string;
  'InlineReferenceCard__spinner--enter': string;
  'InlineReferenceCard__spinner--enter-active': string;
  'InlineReferenceCard__spinner--exit': string;
  'InlineReferenceCard__spinner--exit-active': string;
}

export const locals: IInlineReferenceCardCss;
