// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export interface IAssetCardCss {
  'AssetCard': string;
  'AssetCard__asset': string;
  'AssetCard__header': string;
  'AssetCard__header__dropdown-button': string;
}

export const locals: IAssetCardCss;
