export { Heading } from './Heading/Heading';
export type { HeadingProps, HeadingElement } from './Heading/Heading';
export { Subheading } from './Subheading/Subheading';
export type { SubheadingProps } from './Subheading/Subheading';
export { Typography } from './Typography';
export type { TypographyProps } from './Typography';
export { DisplayText } from './DisplayText/DisplayText';
export type { DisplayTextProps } from './DisplayText/DisplayText';
export { SectionHeading } from './SectionHeading/SectionHeading';
export type { SectionHeadingProps } from './SectionHeading/SectionHeading';
export { Paragraph } from './Paragraph/Paragraph';
export type { ParagraphProps } from './Paragraph/Paragraph';
export { Text } from './Text/Text';
export type { TextProps } from './Text/Text';
