name: Changelog Test

on:
  push:
    branches:
      - "changesets-test-ci"
  workflow_dispatch:

jobs:
  daily:
    if: ${{ 'contentful/forma-36' == github.repository }}
    name: Changelog Test
    runs-on: ubuntu-latest
    steps:
      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: changesets-test-ci

      - name: Setup Node.js 14.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.0

      - name: Load Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate the new changelog
        run: yarn changelog:write

      - name: Commit changelog
        run: yarn changelog:commit
