name: Deploy CDN to Fastly Compute

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.actor != 'renovate[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24.18.1
      - uses: pnpm/action-setup@008330803749db0355799c700092d9a85fd074e9 # v6.0.9
      - name: Install dependencies
        run: pnpm --filter @contentful/f36-cdn install --frozen-lockfile
      - name: Deploy to Compute
        uses: fastly/compute-actions@a25cf83ef5c19ef7d86f1eebffcd8f6c02ddc786 # v14
        with:
          project_directory: packages/cdn
          service_id: ${{ secrets.CDN_FASTLY_SERVICE_ID }}
        env:
          FASTLY_API_TOKEN: ${{ secrets.CDN_FASTLY_TOKEN }}
