name: "npm-package-publisher"

on:
  registry_package:
    types: [published]

jobs:
  worker:
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: contentful/npm-package-publisher
          ref: v1.0
          token: ${{ secrets.GITHUB_TOKEN  }}
          path: ./action
      - name: Run my action
        uses: ./action
        with:
          VAULT_URL: ${{ secrets.VAULT_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_ACCESS: "public"